FROM node:20 AS builder
run mkdir -p /app
WORKDIR /app
COPY package*.json /app
RUN npm ci
COPY . .

# TODO: Args

# TODO: Env

RUN npx prisma generate
RUN npm run build
RUN npm prune --production

FROM node:20

ENV NODE_ENV production

RUN mkdir -p /app
WORKDIR /app
COPY --from=builder /app/build build/
COPY --from=builder /app/node_modules node_modules/
COPY package.json

EXPOSE 3000
CMD [ "node", "build" ]
